<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260707092648 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appointment_verification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_first_name VARCHAR(100) NOT NULL, client_last_name VARCHAR(100) NOT NULL, client_email VARCHAR(180) NOT NULL, client_phone VARCHAR(30) DEFAULT NULL, message TEXT DEFAULT NULL, code VARCHAR(6) NOT NULL, attempts INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consultation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A333D20662FF6CDF ON appointment_verification (consultation_id)');
        $this->addSql('ALTER TABLE appointment_verification ADD CONSTRAINT FK_A333D20662FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointment_verification DROP CONSTRAINT FK_A333D20662FF6CDF');
        $this->addSql('DROP TABLE appointment_verification');
    }
}
